const acceptCategory = {
  Ly: "Ly",
  Chén: "Chén",
  "Nhẫn midi": "Nhẫn",
  "Nhẫn khắc dấu": "Nhẫn",
  "Nhẫn đôi": "Nhẫn",
  "Nhẫn đính đá": "Nhẫn",
  "Nhẫn cưới": "Nhẫn",
  "Dây chuyền pha lê": "Dây chuyền",
  "Dây chuyền đá": "Dây chuyền",
  "Dây chuyền cameo": "Dây chuyền",
  "Mặt dây chuyền": "Dây chuyền",
  "Dây chuyền quyến rũ": "Dây chuyền",
  "Vòng tay đính cườm": "Vòng tay",
  "Vòng tay chuỗi": "Vòng tay",
  "Vòng tay vải": "Vòng tay",
  "Vòng tay cứng": "Vòng tay",
  "Quần dài": "Quần",
  "Quần thun": "Quần",
  "Quần lót": "Quần",
  "Quần short": "Quần",
  "Áo thun": "Áo",
  "Áo sơ mi": "Áo",
  "Áo khoác": "Áo",
  "Áo polo": "Áo",
  "Áo nỉ": "Áo",
  "Áo lót": "Áo",
  "Quai hậu và dép": "Giày dép",
  "Giày thể thao": "Giày dép",
  Bốt: "Giày dép",
  "Giày lười": "Giày dép",
  "Khuyên tai vòng": "Khuyên tai",
  "Khuyên tai chùm": "Khuyên tai",
  "Khuyên  tai đơn": "Khuyên tai",
  "Khuyên tai treo": "Khuyên tai",
  Đũa: "Đũa",
  Ghế: "Ghế",
  Bàn: "Bàn",
  Đèn: "Đèn",
  "Board game": "Board game",
  "Trò chơi xếp hình": "Trò chơi xếp hình",
  "Búp bê": "Búp bê",
  "Thú nhồi bông": "Thú nhồi bông",
  "Đồ chơi trẻ em": "Đồ chơi trẻ em",
  "Trang trí tường": "Trang trí nội thất",
  "Trang trí bàn & kệ": "Trang trí nội thất",
  "Trang trí phòng ngủ": "Trang trí nội thất",
  "Trang trí bếp": "Trang trí nội thất",
  "Trang trí phòng khách": "Trang trí nội thất",
};
// const data = "Boardgame";

// // Tìm nhãn tương ứng với dữ liệu
// const label = acceptCategory[data];

// console.log("Nhãn tương ứng:", label);
module.exports = acceptCategory;
